import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";

const CairoFont = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={` ${CairoFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
